// A curated library of lucide icons that read well as small (14-18px) glyphs for equipment
// stat/resistance presets — RPG-flavored: weapons & armor, elements, buffs/debuffs, misc
// fantasy motifs. Keyed by a stable string name (stored on StatPreset.icon) rather than the
// component itself, so presets serialize cleanly to JSON.
import {
  Sword,
  Swords,
  Shield,
  ShieldCheck,
  ShieldAlert,
  HardHat,
  Gem,
  Crown,
  Flame,
  FlameKindling,
  Snowflake,
  Zap,
  Skull,
  Heart,
  Droplet,
  Wind,
  Clover,
  Target,
  Crosshair,
  Footprints,
  Eye,
  Star,
  Anvil,
  Hammer,
  Axe,
  Feather,
  Moon,
  Sun,
  SunSnow,
  Cloud,
  CloudRain,
  Leaf,
  Bug,
  Ghost,
  FlaskConical,
  Beaker,
  Magnet,
  Compass,
  Timer,
  Gauge,
  Activity,
  TrendingUp,
  Bone,
  Scroll,
  Book,
  Key,
  Lock,
  Castle,
  Mountain,
  Waves,
  Biohazard,
  Radiation,
  Orbit,
  Atom,
  Dna,
  Wand,
  Sparkles,
  type LucideIcon,
} from "lucide-react";

export const STAT_ICONS: Record<string, LucideIcon> = {
  sword: Sword,
  swords: Swords,
  shield: Shield,
  shield_check: ShieldCheck,
  shield_alert: ShieldAlert,
  hard_hat: HardHat,
  gem: Gem,
  crown: Crown,
  flame: Flame,
  flame_kindling: FlameKindling,
  snowflake: Snowflake,
  zap: Zap,
  skull: Skull,
  heart: Heart,
  droplet: Droplet,
  wind: Wind,
  clover: Clover,
  target: Target,
  crosshair: Crosshair,
  footprints: Footprints,
  eye: Eye,
  star: Star,
  anvil: Anvil,
  hammer: Hammer,
  axe: Axe,
  feather: Feather,
  moon: Moon,
  sun: Sun,
  sun_snow: SunSnow,
  cloud: Cloud,
  cloud_rain: CloudRain,
  leaf: Leaf,
  bug: Bug,
  ghost: Ghost,
  flask: FlaskConical,
  beaker: Beaker,
  magnet: Magnet,
  compass: Compass,
  timer: Timer,
  gauge: Gauge,
  activity: Activity,
  trending_up: TrendingUp,
  bone: Bone,
  scroll: Scroll,
  book: Book,
  key: Key,
  lock: Lock,
  castle: Castle,
  mountain: Mountain,
  waves: Waves,
  biohazard: Biohazard,
  radiation: Radiation,
  orbit: Orbit,
  atom: Atom,
  dna: Dna,
  wand: Wand,
  sparkles: Sparkles,
};

export const STAT_ICON_NAMES = Object.keys(STAT_ICONS);

export function statIcon(name: string | undefined): LucideIcon {
  return (name && STAT_ICONS[name]) || Star;
}
