// GameMaker Exporter — see docs/14_Export_System.md
// Generates .gml matching the project's existing hand-written item_define()/rarity_define() calls
// exactly, so a generated file can replace a hand-written one with zero other changes.

import type { ItemObject, ItemStats, Project, RarityObject } from "../types/database";

function gmlString(s: string): string {
  return `"${s.replace(/"/g, '\\"')}"`;
}

function statsToGml(stats: ItemStats): string {
  const keys = Object.keys(stats).sort(); // stable, alphabetical order for clean diffs (14_Export_System.md)
  if (keys.length === 0) return "{}";
  const parts = keys
    .filter((k) => stats[k] !== undefined)
    .map((k) => `${k}:${stats[k]}`);
  return `{ ${parts.join(", ")} }`;
}

function itemToGml(item: ItemObject): string {
  const fields: string[] = [];
  fields.push(`name:${gmlString(item.name)}`);
  fields.push(`desc:${gmlString(item.description)}`);
  fields.push(`sprite:${item.sprite || `spr_item_${item.id}`}`);
  if (item.overlay) fields.push(`overlay:${item.overlay}`);
  fields.push(`type:${gmlString(item.type)}`);
  if (item.type === "equip" && item.slot) fields.push(`slot:${gmlString(item.slot)}`);
  fields.push(`rarity:${gmlString(item.rarityId)}`);
  fields.push(`quest:${item.quest}`);
  fields.push(`value:${item.value}`);
  fields.push(`stack:${item.stack}`);
  fields.push(`stats:${statsToGml(item.stats)}`);

  return `    item_define(${gmlString(item.id)}, {\n        ${fields.join(",\n        ")}\n    });`;
}

function colorStyleToGml(style: RarityObject["style"]): string {
  const hexToRgb = (hex: string) => {
    const h = hex.replace("#", "");
    const r = parseInt(h.substring(0, 2), 16);
    const g = parseInt(h.substring(2, 4), 16);
    const b = parseInt(h.substring(4, 6), 16);
    return `make_colour_rgb(${r},${g},${b})`;
  };
  const c1 = hexToRgb(style.c1);
  const c2 = style.c2 ? hexToRgb(style.c2) : undefined;
  const args = [gmlString(style.kind), c1];
  if (c2) args.push(c2);
  if (style.speed !== undefined) args.push(String(style.speed));
  return `color_style(${args.join(", ")})`;
}

function rarityToGml(rarity: RarityObject): string {
  return `    rarity_define(${gmlString(rarity.id)}, ${gmlString(rarity.name)},\n        ${colorStyleToGml(
    rarity.style
  )},\n        ${rarity.order});`;
}

export interface ExportWarning {
  severity: "warning" | "error" | "info";
  message: string;
  objectId: string;
}

export interface ExportResult {
  files: { path: string; content: string }[];
  warnings: ExportWarning[];
}

export function exportToGameMaker(project: Project): ExportResult {
  const warnings: ExportWarning[] = [];

  for (const item of project.items) {
    if (Object.values(item.stats).some((v) => v !== undefined && Math.abs(v) >= 9999)) {
      warnings.push({
        severity: "warning",
        objectId: item.id,
        message:
          "Suspicious stat magnitude (e.g. -99999) — likely a min-clamp hack. Consider a dedicated speed_override field. Not required.",
      });
    }
    if (item.type === "equip" && !item.overlay) {
      warnings.push({
        severity: "info",
        objectId: item.id,
        message: "No worn appearance (overlay) set — item will be invisible on the character when equipped.",
      });
    }
  }

  const itemsFile = [
    "/// scr_items_generated — auto-generated by RPG Narrative Studio, do not edit by hand",
    "/// see docs/14_Export_System.md — Field Mapping: Items",
    "function items_init_generated() {",
    "    global.items = {};",
    ...project.items.map(itemToGml),
    "}",
    "",
  ].join("\n");

  const rarityFile = [
    "/// scr_rarity_generated — auto-generated by RPG Narrative Studio, do not edit by hand",
    "/// see docs/14_Export_System.md — Field Mapping: Rarity",
    "function rarity_init_generated() {",
    "    global.rarities = {};",
    ...project.rarities.slice().sort((a, b) => a.order - b.order).map(rarityToGml),
    "}",
    "",
  ].join("\n");

  return {
    files: [
      { path: "Export/GameMaker/scr_items_generated.gml", content: itemsFile },
      { path: "Export/GameMaker/scr_rarity_generated.gml", content: rarityFile },
    ],
    warnings,
  };
}
